# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20160606_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='polygon',
            new_name='geometry',
        ),
    ]
